version: '3.1'
services :
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - "/data/postgres:/data/postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
      PGDATA: /data/postgres
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8082:8080
